### ISSUE TITLE
Plugins do not recognize mysqloo as installed. 

### ISSUE THREAD

**Issue by mbaehr2909** [syl0r/MySQLOO#12]
After putting the two required files in the corresponding Directories, I still keep getting the error message, that mysqloo is not installed correctly.

**Comment by Kefta** [comment]
What folder did you put the module in? What did you name it? What OS are you on?

**Comment by mbaehr2909** [comment]
The Server is running Linux, but I do not know exactly which version. I kept the Filenames as they were downloaded (libmysqlclient.so.18 in the root folder, and gmsv_mysqloo_linux.dll in the lua/bin folder). Which Module do you mean?

**Comment by syl0r** [comment]
He meant what folder did you put the mysqloo dll file in. 
Also, what error message are you getting exactly?

**Comment by mbaehr2909** [comment]
From e.g. KLib I keep on getting the following error Message:
Wed Sep 20 15:28:47 2017 - [LibK] FATAL: Couldn't load mysqloo, make sure it is correctly installed! errror was: attempt to index a string value
Wed Sep 20 15:28:47 2017 - MySQL Error: MySQLOO modules aren't installed properly!
Wed Sep 20 15:28:54 2017 - [LibK] Error initializing player Hardwave3[DTJ](0: SQL Error )
Wed Sep 20 15:28:55 2017 - [LibK] Error initializing player Pickle Rick(0: SQL Error )

Do you mean the gmsv_mysqloo_linux.dll file? I have put this in garrysmod/lua/bin (although I had to create the bin folder).

**Comment by syl0r** [comment]
Run the server in sandbox and put

> lua_run require("mysqloo")
in console, see what error (if at all) is printed

**Comment by mbaehr2909** [comment]
It gives me the error 
[ERROR] attempt to index a string value
1. unknown - [C]:-1
2. require - [C]:-1
3. unknown - lua_run:1

**Comment by ZacharyDuBois** [comment]
I get the same error. Debian 8 64bit, require fails to load mysqloo with "attempt to index a string value" using provided binaries placed in the correct directories.

**Comment by syl0r** [comment]
That sounds weird and shouldn't happen. I am currently unable to look into it unfortunately but I will do so once I am.

**Comment by mbaehr2909** [comment]
Alright. Thanks.

**Comment by mbaehr2909** [comment]
Hi sly0r, did you find anything?

**Comment by TG4LAaron** [comment]
Same here on windows and linux on mysqloo 9.5
ERROR] attempt to index a string value

unknown - [C]:-1
require - [C]:-1
unknown - lua_run:1

But when i use MySQLOO 9.4 it works all ok and good no errors

**Comment by syl0r** [comment]
Alright, I am back in a position where I can actually do stuff. I tested the 9.5 release on both a linux and windows server and they appeared to be working fine.
Is your  gmod server maybe severely outdated and does not support the new gmod headers? Can anyone confirm that their server is running the latest gmod version?

**Comment by TG4LAaron** [comment]
Yep running on latest version will give linux ago 1 more time

**Comment by TG4LAaron** [comment]
Ye seems to be working on linux now
