### ISSUE TITLE
Installation probelm

### ISSUE THREAD

**Issue by BadWorksFun** [syl0r/MySQLOO#14]
Do I install the whole file into my autorun/bin or do I only install the Mysqloo inside of the Mysqloo-9.5

also... why does the file order look so different then my old Mysql8

where it goes MySqlOO\lua\includes\modules

                       MySqlOO\info.txt

                       MySqlOO\lua\test\MySqlOO

Old MySQLOO Attached so you can see for self what I mean.

[MySqlOO.zip](https://github.com/syl0r/MySQLOO/files/1384233/MySqlOO.zip)

**Comment by syl0r** [comment]
The binary files need to go into the gmod/lua/bin folder, you placed them in includes for some reason.
