### ISSUE TITLE
Facepunch Post is dead

### ISSUE THREAD

**Issue by 332481717096** [syl0r/MySQLOO#16]
How can I install this on linux? The facepunch forums have been redone or something and I can't access the post for how to install it. Thanks.

**Comment by masterstreamer** [comment]
Same for me.

**Comment by syl0r** [comment]
Oh Garry you idiot....
I will repost it on the new Gmod forums soon.....

**Comment by syl0r** [comment]
Alright, I fixed the old one, you can find it here:
https://forum.facepunch.com/f/gmodaddon/jjdq/gmsv-mysqloo-v9-Rewritten-MySQL-Module-prepared-statements-transactions/1/
