### ISSUE TITLE
Add ability to set CLIENT flags

### ISSUE THREAD

**Issue by Kefta** [syl0r/MySQLOO#2]
Located here: https://github.com/syl0r/MySQLOO/blob/8d424af773df1cbb6cc6cea70d9db09401a5eac3/MySQL/include/mysql_com.h#L159-L239

**Comment by syl0r** [comment]
The reason I don't expose that function to lua is that I simply don't support many of these options being changed because it might break mysqloo.
Are there really any other flags that are important? If so I could just create setters for them instead.

**Comment by Kefta** [comment]
Ah, it looks like the module already supports multiple statements and result sets by default, so I guess the only flags I see any personal use are CLIENT_SECURE_CONNECTION and CLIENT_LONG_PASSWORD (although that might be set by default now).
