### ISSUE TITLE
Retrieve sql from prepared query

### ISSUE THREAD

**Issue by end360** [syl0r/MySQLOO#6]
Please add the abiliity to retrieve a copy of the sql that was/should've been run by a prepared query. This way, if an error happens I can add the sql to a queue to run without having to store the variables, in case one of the variables changes (the player leaves, or some other thing).

**Comment by syl0r** [comment]
I don't really understand the problem? What kind of error do you expect to happen? If the connection drops, it should attempt to reconnect while the query is running without it failing the query. If another error happens then usually no matter how many queries you send, it's always going to error, no?

If you somehow do require that behavior, then you can just restart a prepared query using query:start() and it should still have the same data as before. This of course only works if you don't reuse the prepared query objects.

**Comment by SleepyMode** [comment]
Hey there,
I believe he wants the ability to extract the currently stored information inside a query without being forced to put it in a variable(for whatever weird reason).
