### ISSUE TITLE
Error - no MetaName string type for userdata (AGH!)

### ISSUE THREAD

**Issue by markusmarkusz** [syl0r/MySQLOO#7]
After updating MySQLOO to Version 9.4 the following message was spammed into my command line interface:
```
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
Error - no MetaName string type for userdata (AGH!)
```
There is no chance that this error is caused by anything else than MySQLOO.
It would be nice if you fix the problem that causes this message.

**Comment by syl0r** [comment]
I assume the error is caused by you trying to print something that you really shouldn't, maybe you are using PrintTable on a query object?

**Comment by markusmarkusz** [comment]
This message come's when the server is fully initialized. I don't think that there is anything that prints a query object.
The message has never been written to the console so often. This is only since I have updated the module.

**Comment by syl0r** [comment]
It appears that this error is caused when you try to call type on a query object like this:
`lua_run type(db:query("").___lua_userdata_object)
> type(db:query("").___lua_userdata_object)...
Error - no MetaName string type for userdata (AGH!)`
I don't see why you would call type on the userdata object?

**Comment by markusmarkusz** [comment]
I don't call something like this.
Could it be that the Pointshop uses this somewhere?

**Comment by syl0r** [comment]
Potentially, in that case please contact the pointshop coders about this, it's not something that should happen in good code.

**Comment by markusmarkusz** [comment]
I'll check this again.
Until this, I simply leave this issue open if it's okay for you.

**Comment by markusmarkusz** [comment]
Do you know any easy way to check if the Pointshop uses that somewhere?
I just wanted to override `type()` and run `debug.Trace()`, but this turned out to be less intelligent. xD

**Comment by syl0r** [comment]
Unfortunatley not, considering that many people use pointshop I'd say it's very unlikely to be caused by it, since this would've also happened with old versions of mysqloo.

**Comment by markusmarkusz** [comment]
This message isn't new. The only thing which is new is that the message is spammed so often.
There are only two things that are using MySQLOO:
- Pointshop 2 / LibK
- AtlasChat

**Comment by Kefta** [comment]
Try removing them and see if the message goes away?
